### ISSUE TITLE
How to load saved images in gallery to show the already trained person

### ISSUE THREAD

**Issue by bbhushan-ds** [szagoruyko/torch-opencv-demos#10]
Hi All,

How to load saved images in gallery to show the already trained person. I need to show the trained people again in gallery if the whole system/demo restarted.

After a long research, I could not find a way to load a image in gallery which was saved on disk before restart of demo. 

  local img = image.load(file, 3, 'byte')

  local faceInGallery = gallery
                    :narrow(1, 1 + thumbnailSize*(currentPerson-1), thumbnailSize)
                    :narrow(2, 101 + thumbnailSize \* #people[currentPerson], thumbnailSize)

  -- show image in gallery
  cv.resize{ **img** , {thumbnailSize, thumbnailSize}, dst=faceInGallery}

Please help me to show image in cv.resize which can be displayed in gallery.

Thanks
Bharat Bhushan

**Comment by shrubb** [comment]
Hi, you're almost right, but use cv.imread instead of image.load.

**Comment by bbhushan-ds** [comment]
Thanks you very much. Its been solved
