### ISSUE TITLE
File already exists in database: caffe.proto error

### ISSUE THREAD

**Issue by appupulla** [szagoruyko/torch-opencv-demos#11]
Hello,
Please Help!!!
OS: Mac OS Sierra
Open CV: 3.0.0
protobuf: 3.1.0

When i am trying to run the age-gender detection code,  i am getting the following error:
[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: caffe.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1272] CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
Abort trap: 6

This is happening when i try require cv after require load caffe or the other way round. Please help me solve this issue. I am stuck since two days debugging this bad boy

**Comment by szagoruyko** [comment]
@appupulla this happens because protobuf library cannot be loaded twice, and they included it in OpenCV apparently. You have two options:
- use loadcaffe to save network in t7 format without importing opencv
- compile opencv without protobuf

**Comment by appupulla** [comment]
can you please elaborate on the above steps? I am sorry, I am very new to this.

**Comment by pyrolitic** [comment]
For the second option, change the Makefile.config file to have the line `USE_OENCV := 0` uncommented. Then recompile with `make`.
