### ISSUE TITLE
age_gender_mean.t7 lost

### ISSUE THREAD

**Issue by huxdhxa** [szagoruyko/torch-opencv-demos#20]
Hello Everyone:
         "https://dl.dropboxusercontent.com/u/44617616/age_gender_mean.t7", this file can not download now.
Can you Re upload it. Or send me email 529766319@qq.com 
Thank You!!

**Comment by szagoruyko** [comment]
here is one: <https://www.dropbox.com/s/wa61ihl8l9z89e8/age_gender_mean.t7?dl=0>

**Comment by huxdhxa** [comment]
Thank You very much!
