### ISSUE TITLE
"input.dims() == 4 error", How to convert Mat(2 dims) to 4 dims

### ISSUE THREAD

**Issue by huxdhxa** [szagoruyko/torch-opencv-demos#21]
Hello Everyone:
          I'm testing "gender_net.caffemodel" with Opencv in C++, like this:
Mat img1 = imread("1.jpg",0);//read a gray image
resize(img1, img1, Size(227, 227));
Mat img2;
img1.convertTo(img2, CV_32F);

dnn::Blob inputBlob = dnn::Blob(img2);
net.setBlob(".data", inputBlob);        //set the network input 
net.forward();

        when run "net.forward();", take failed:
OpenCV Error: Assertion failed (input.dims() == 4
        So,I want to know, How to convert Mat(2 dims) to 4 dims in C++
Thanks!

**Comment by shrubb** [comment]
Search OpenCV docs for that. Should be something like `reshape`.

Not related to demos, so closing the issue.

**Comment by huxdhxa** [comment]
OK,Thanks for your reply
