### ISSUE TITLE
In Live Image Classification, show percentage of each 5 most probable class names

### ISSUE THREAD

**Issue by fayjie** [szagoruyko/torch-opencv-demos#22]
Now I know the 5 most probable class names in frame, can I get the percentage for each name?

**Comment by shrubb** [comment]
In this line

```lua
local _,classes = net:forward(I):view(-1):float():sort(true)
```

the first value returned by `sort` is actually what you need -- the probabilities. So you can rename `_` to for example `confidences` and use it as you want.

**Comment by fayjie** [comment]
Thanks!! It really helps.
