### ISSUE TITLE
face_recognition demo: segmentation fault error

### ISSUE THREAD

**Issue by kaisark** [szagoruyko/torch-opencv-demos#25]
Running into segmentation fault errors with face_recognition and age_gender demos using the webcam.

System:
Nvidia TX1
4 GB RAM
Ubuntu 16
opencv 3.1 with cuda

-----------------------------
nvidia@tegra-ubuntu:~/torch-opencv-demos/age_gender$ th demo.lua camera
Looking for haarcascades/haarcascade_frontalface_default.xml...	
Successfully loaded ./gender_net.caffemodel
Successfully loaded ./age_net.caffemodel
Segmentation fault

**Comment by shrubb** [comment]
Also tried to fix, please update and try again

**Comment by kaisark** [comment]
I did a git pull today. Face_recognition gets a little further along, but age_gender seg faults immediately. I moved age_gender into a separate issue. Face_recognition runs for a few seconds and then crashes...

--------------------------------------------------------------
nvidia@tegra-ubuntu:~/torch-opencv-demos/age_gender$ th demo.lua camera
Looking for haarcascades/haarcascade_frontalface_default.xml...	
Successfully loaded ./gender_net.caffemodel
Successfully loaded ./age_net.caffemodel
Segmentation fault


----------------------------------------------------------------

nvidia@tegra-ubuntu:~/torch-opencv-demos/face_recognition$ th demo.lua camera 1 kaisar
	
================== Use 1..9 keys to change the person to be labeled ==================	
==================        Double-click the face to label it         ==================	
==================         Press Space to pause the stream          ==================	
	
Looking for haarcascades_cuda/haarcascade_frontalface_default.xml...	
Loading the network...	
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-391/cutorch/lib/THC/generic/THCStorage.c line=182 error=17 : invalid device pointer
Segmentation fault



![screenshot from 2018-03-30 00-50-50](https://user-images.githubusercontent.com/3580312/38125067-c524045e-33b4-11e8-9974-6d720a961da1.png)

![screenshot from 2018-03-30 01-54-00](https://user-images.githubusercontent.com/3580312/38126272-83eab5ce-33bd-11e8-9543-98a852846861.png)

**Comment by shrubb** [comment]
Oh, I finally found the error (there's been a CUDA memory management bug since so long ago). I'm going to fix it soon, stay tuned.

**Comment by shrubb** [comment]
@kaisark Please redo `luarocks install cv` and try again, should work now.

**Comment by kaisark** [comment]
I rebuilt cv. Face Recognition seems to be working now. I noticed that non-max suppression prob needs to be added...

Thanks.

nvidia@tegra-ubuntu:~/torch-opencv-demos/face_recognition$ th demo.lua camera 1 kaisar

![screenshot from 2018-04-24 00-02-29](https://user-images.githubusercontent.com/3580312/39165644-7fff2ebe-4753-11e8-969f-9832e5b7669d.png)
