### ISSUE TITLE
Warning: Failed to load function from bytecode: (binary): cannot load incompatible 

### ISSUE THREAD

**Issue by kaisark** [szagoruyko/torch-opencv-demos#26]
I am running into an error running the imagenet_classification demo (see error below):

System:
Nvidia TX1
4 GB RAM
Ubuntu 16
opencv 3.1 with cuda
Torch 7

nvidia@tegra-ubuntu:~/neuraltalk2$ luajit -v
LuaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/

demo.lua:
print '==> Loading network'
-- Using network in network http://openreview.net/document/9b05a3bb-3a5e-49cb-91f7-0f482af65aea
local net = torch.load(network_name):unpack():float()
local synset_words = torch.load('synset.t7','ascii')

--------------------------------------------------------------------------
nvidia@tegra-ubuntu:~/torch-opencv-demos/imagenet_classification$ th demo.lua 
==> Downloading image and network	
image_name: Goldfish3.jpg	
network_name: nin_nobn_final.t7	
==> Loading network	
Warning: Failed to load function from bytecode: (binary): cannot load incompatible bytecode/home/nvidia/torch/install/bin/luajit: demo.lua:29: attempt to call method 'unpack' (a nil value)
stack traceback:
	demo.lua:29: in main chunk
	[C]: in function 'dofile'
	...idia/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x004061f0

**Comment by shrubb** [comment]
Changed loading code a bit, could you try now?

**Comment by kaisark** [comment]
I did a git pull today. New code ("local net = torch.load(network_name).model:float()") update seems to run, though the "Failed to load function from bytecode" message still prints to the console (safe to ignore?).

--------------------------------
nvidia@tegra-ubuntu:~/torch-opencv-demos/imagenet_classification$ th demo.lua camera
==> Downloading image and network	
==> Loading network	
Warning: Failed to load function from bytecode: (binary): cannot load incompatible bytecode^C/home/nvidia/torch/install/bin/luajit: /home/nvidia/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 8 module of nn.Sequential:
/home/nvidia/torch/install/share/lua/5.1/nn/THNN.lua:110: interrupted!
stack traceback:
	/home/nvidia/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialConvolutionMM_updateOutput'
	...ia/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:79: in function <...ia/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:76>
	[C]: in function 'xpcall'
	/home/nvidia/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/nvidia/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	demo.lua:41: in main chunk
	[C]: in function 'dofile'
	...idia/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x004061f0

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/nvidia/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/nvidia/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	demo.lua:41: in main chunk
	[C]: in function 'dofile'
	...idia/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x004061f0
^C

![torch gif-downsized_large](https://user-images.githubusercontent.com/3580312/38125506-ecb6fbe0-33b7-11e8-8694-4255cb61ce14.gif)

**Comment by shrubb** [comment]
Yes, if it runs, I think the message can be ignored safely.
